name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Set up environment variables
        shell: bash
        run: |
          BASE_MAJOR=3
          BASE_MINOR=6
          BASE_PATCH=9

          # 当前这次 run 76 对应 3.6.9
          BASE_RUN_NUMBER=76

          CURRENT_RUN=${{ github.run_number }}
          PATCH=$(( BASE_PATCH + CURRENT_RUN - BASE_RUN_NUMBER ))

          VERSION="${BASE_MAJOR}.${BASE_MINOR}.${PATCH}"
          CURRENT_DATE="$(date +'%Y%m%d')"
          RELEASE_TITLE="天行键v${VERSION}"

          echo "CURRENT_RUN=${CURRENT_RUN}"
          echo "VERSION=${VERSION}"

          echo "CURRENT_DATE=${CURRENT_DATE}" >> "$GITHUB_ENV"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
          echo "RELEASE_TITLE=${RELEASE_TITLE}" >> "$GITHUB_ENV"

      - name: Checkout main branch
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Zip main branch files excluding .git and .github
        run: zip -r txjx.zip . -x "*.git*" -x "*.github*"

      - name: Create Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_DATE }}
          release_name: ${{ env.RELEASE_TITLE }}
          body: |
            Release
          draft: false
          prerelease: false

      - name: Upload txjx.zip to Release
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./txjx.zip
          asset_name: txjx.zip
          asset_content_type: application/zip
