name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Set up environment variables
        shell: bash
        run: |
          BASE_MAJOR=3
          BASE_MINOR=6
          BASE_PATCH=5

          # 从哪一次 workflow run_number 开始算 3.6.5
          # 例如当前 run_number 是 238，并且这次要发布 3.6.5，就填 238
          BASE_RUN_NUMBER=365

          CURRENT_RUN=${{ github.run_number }}
          PATCH_OFFSET=$(( (CURRENT_RUN - BASE_RUN_NUMBER) / 1 ))
          PATCH=$(( BASE_PATCH + PATCH_OFFSET ))

          VERSION="${BASE_MAJOR}.${BASE_MINOR}.${PATCH}"
          CURRENT_DATE="$(date +'%Y%m%d')"
          RELEASE_TITLE="天行键$(date +'%Y.%m.%d') v${VERSION} 词库更新"

          echo "CURRENT_DATE=${CURRENT_DATE}" >> "$GITHUB_ENV"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
          echo "RELEASE_TITLE=${RELEASE_TITLE}" >> "$GITHUB_ENV"

      - name: Checkout main branch
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Zip main branch files excluding .git and .github
        run: zip -r txjx.zip . -x "*.git*" -x "*.github*"

      - name: Create Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_DATE }}
          release_name: ${{ env.RELEASE_TITLE }}
          body: |
            Release
        draft: false
        prerelease: false

      - name: Upload txjx.zip to Release
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./txjx.zip
          asset_name: txjx.zip
          asset_content_type: application/zip
